# Generated by Django 3.1 on 2024-07-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesevapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filerecord',
            table='file_record',
        ),
    ]
